name: Tests
on:
  push:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1.4
      with:
        run: yarn test
